<a href="https://colab.research.google.com/github/at13lemmewrite/PGDM-/blob/main/pgdm_lecture_1_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Lecture2_data.xlsx to Lecture2_data.xlsx

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel("Lecture2_data.xlsx")

In [ ]:
print("below is the head of the sheet \n")
print(df.head)
print("\n below is the tail of the sheet")
print(df.tail)

below is the head of the sheet

<bound method NDFrame.head of    Record_ID         Product       City Quarter  Students_Enrolled  \
0       R001     WhiteHat Jr    Kolkata      Q2                243
1       R002     WhiteHat Jr     Mumbai      Q3                356
2       R003  Aakash Classes    Kolkata      Q3                734
3       R004           Toppr  Bengaluru      Q4                561
4       R005            Osmo  Bengaluru      Q2                331
..       ...             ...        ...     ...                ...
95      R096           Toppr      Delhi      Q4                517
96      R097  Aakash Classes     Mumbai      Q4                937
97      R098     WhiteHat Jr     Mumbai      Q2                371
98      R099  Aakash Classes  Bengaluru      Q1                807
99      R100            Osmo     Mumbai      Q4                414

    Avg_Fee_INR  Discount_Pct  Revenue_Lakh  Marketing_Spend_Lakh  \
0         46500          18.0          92.7                 247.0
1         44000          21.5         123.2                 353.1
2         93200          15.9         575.7                 114.6
3         19500          18.5          89.3                 153.7
4         12200          14.2          34.8                  82.6
..          ...           ...           ...                   ...
95        19700          20.8          80.7                 172.0
96        85300          21.6         626.6                 182.3
97        43200          17.3         132.8                 335.6
98        88100           9.6         643.0                 130.7
99        12100          20.7          39.8                 102.1

    Content_Cost_Lakh  Salary_Cost_Lakh  Other_Cost_Lakh  Sales_Team_Size  \
0                49.9             109.2             39.2               20
1                71.3             105.8             40.6               33
2                88.1             203.9             90.4               17
3                67.4              80.7             34.3               17
4                41.1              48.5             16.3               11
..                ...               ...              ...              ...
95               62.5              72.9             29.0               19
96              133.9             210.7            111.4               27
97               67.8             101.7             41.7               31
98              112.0             185.4             97.1               22
99               48.0              48.2             22.1               12

    Refund_Pct  Customer_Rating
0          8.4              3.9
1          7.4              4.0
2          4.7              4.3
3          8.3              3.7
4          3.2              4.2
..         ...              ...
95         9.4              3.8
96         7.9              4.0
97         6.2              3.9
98         3.9              4.3
99         7.2              4.4

[100 rows x 15 columns]>

 below is the tail of the sheet
<bound method NDFrame.tail of    Record_ID         Product       City Quarter  Students_Enrolled  \
0       R001     WhiteHat Jr    Kolkata      Q2                243
1       R002     WhiteHat Jr     Mumbai      Q3                356
2       R003  Aakash Classes    Kolkata      Q3                734
3       R004           Toppr  Bengaluru      Q4                561
4       R005            Osmo  Bengaluru      Q2                331
..       ...             ...        ...     ...                ...
95      R096           Toppr      Delhi      Q4                517
96      R097  Aakash Classes     Mumbai      Q4                937
97      R098     WhiteHat Jr     Mumbai      Q2                371
98      R099  Aakash Classes  Bengaluru      Q1                807
99      R100            Osmo     Mumbai      Q4                414

    Avg_Fee_INR  Discount_Pct  Revenue_Lakh  Marketing_Spend_Lakh  \
0         46500          18.0          92.7                 247.0
1         44000          21.5         123.2                 353.1
2         93200          15.9         575.7                 114.6
3         19500          18.5          89.3                 153.7
4         12200          14.2          34.8                  82.6
..          ...           ...           ...                   ...
95        19700          20.8          80.7                 172.0
96        85300          21.6         626.6                 182.3
97        43200          17.3         132.8                 335.6
98        88100           9.6         643.0                 130.7
99        12100          20.7          39.8                 102.1

    Content_Cost_Lakh  Salary_Cost_Lakh  Other_Cost_Lakh  Sales_Team_Size  \
0                49.9             109.2             39.2               20
1                71.3             105.8             40.6               33
2                88.1             203.9             90.4               17
3                67.4              80.7             34.3               17
4                41.1              48.5             16.3               11
..                ...               ...              ...              ...
95               62.5              72.9             29.0               19
96              133.9             210.7            111.4               27
97               67.8             101.7             41.7               31
98              112.0             185.4             97.1               22
99               48.0              48.2             22.1               12

    Refund_Pct  Customer_Rating
0          8.4              3.9
1          7.4              4.0
2          4.7              4.3
3          8.3              3.7
4          3.2              4.2
..         ...              ...
95         9.4              3.8
96         7.9              4.0
97         6.2              3.9
98         3.9              4.3
99         7.2              4.4

[100 rows x 15 columns]>

In [ ]:
print(df.shape)       # (rows, columns)
print(len(df)   )     # rows only
print(df.shape[0] )   # rows only
print(df.shape[1] )   # columns only
df.info()
print(df.dtypes)

(100, 15)
100
100
15
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Record_ID             100 non-null    object
 1   Product               100 non-null    object
 2   City                  100 non-null    object
 3   Quarter               100 non-null    object
 4   Students_Enrolled     100 non-null    int64
 5   Avg_Fee_INR           100 non-null    int64
 6   Discount_Pct          100 non-null    float64
 7   Revenue_Lakh          100 non-null    float64
 8   Marketing_Spend_Lakh  100 non-null    float64
 9   Content_Cost_Lakh     100 non-null    float64
 10  Salary_Cost_Lakh      100 non-null    float64
 11  Other_Cost_Lakh       100 non-null    float64
 12  Sales_Team_Size       100 non-null    int64
 13  Refund_Pct            100 non-null    float64
 14  Customer_Rating       96 non-null     float64
dtypes: float64(8), int64(3), object(4)
memory usage: 11.8+ KB
Record_ID                object
Product                  object
City                     object
Quarter                  object
Students_Enrolled         int64
Avg_Fee_INR               int64
Discount_Pct            float64
Revenue_Lakh            float64
Marketing_Spend_Lakh    float64
Content_Cost_Lakh       float64
Salary_Cost_Lakh        float64
Other_Cost_Lakh         float64
Sales_Team_Size           int64
Refund_Pct              float64
Customer_Rating         float64
dtype: object

In [ ]:
df.columns = ["r_id", "product", "city", "quarter" , "roll" , "afee" , "dis","rev", "ms", "cc" , "sc", "oc", "sts" , "refund" , "cusrat"]

In [ ]:
df["tc"]=(df["ms"]+ df["cc"]+df["sc"]+df["oc"])
df["prof"]=df["rev"]-df["tc"]
print(df[["product", "tc", "rev", "prof"]].head(10))

          product     tc    rev   prof
0     WhiteHat Jr  445.3   92.7 -352.6
1     WhiteHat Jr  570.8  123.2 -447.6
2  Aakash Classes  497.0  575.7   78.7
3           Toppr  336.1   89.3 -246.8
4            Osmo  188.5   34.8 -153.7
5    Learning App  521.1  228.7 -292.4
6           Toppr  276.9   87.4 -189.5
7  Aakash Classes  554.9  595.5   40.6
8           Toppr  307.7   94.4 -213.3
9     WhiteHat Jr  566.5  114.8 -451.7

In [ ]:
print(df.isna().sum())

r_id       0
product    0
city       0
quarter    0
roll       0
afee       0
dis        0
rev        0
ms         0
cc         0
sc         0
oc         0
sts        0
refund     0
cusrat     4
tc         0
prof       0
dtype: int64

In [ ]:
rating= df["cusrat"].mean()
if rating>=4:
    print("satisfied")
else:
    print("unsatisfied")

satisfied

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Starbucks_India_Sales_Dataset.xlsx to Starbucks_India_Sales_Dataset.xlsx

In [ ]:
import pandas as pd
import numpy as np

FILE = "/content/Starbucks_India_Sales_Dataset.xlsx"

In [ ]:
df=pd.read_excel(FILE, sheet_name="Sales_Data")
p_df=pd.read_excel(FILE,sheet_name="Products" )
s_df=pd.read_excel(FILE,sheet_name="Stores" )
print("sales table", df.shape)
print("product table", p_df.shape)
print("stores table", s_df.shape)
df.head()

sales table (100, 15)
product table (8, 4)
stores table (10, 5)

,OrderID,Date,City,StoreID,Product,Category,Size,Unit_Price,Quantity,Discount_Pct,Revenue,Payment_Mode,Customer_Type,Order_Channel,Rating
0,SBX1001,2026-07-01,Hyderabad,S07,Cappuccino,Hot Coffee,Grande,280,1,0.00,280.0,UPI,New,In-store,4.0
1,SBX1002,2026-07-01,Bengaluru,S05,Cold Brew,Cold Coffee,Tall,300,1,0.10,270.0,UPI,Member,In-store,4.0
2,SBX1003,2026-07-01,Mumbai,S03,Cappuccino,Hot Coffee,Venti,310,1,0.05,294.5,UPI,Returning,In-store,2.0
3,SBX1004,2026-07-02,Hyderabad,S08,Blueberry Muffin,Food,Regular,180,1,0.20,144.0,Wallet,Member,In-store,3.0
4,SBX1005,2026-07-04,Delhi,S01,Latte,Hot Coffee,Grande,300,2,0.20,480.0,Card,Member,In-store,4.0

In [ ]:
#list
menu=["Cappuccino", "Latte" , "Americano", "Cold Brew" ]
#TUPLE
store=("S01", "Connaught Place", "Delhi")
#set
cities={"Delhi", "Mumbai", "Benguluru", "Hyderabad", "Pune", "Delhi"}
#dictionary
price={"Cappaccino" :250, "Latte": 270, "Americano":220, "Cold Brew": 300, "Frappuccino": 350, "Masala Chai": 200, "Blueberry Muffin" : 180, "Veg Sandwich": 240}
print("List :", menu)
print("tuple : ", store)
print("dictionary :", price)

print()
print(type(menu), type(store), type(cities), type(price))

List : ['Cappuccino', 'Latte', 'Americano', 'Cold Brew']
tuple :  ('S01', 'Connaught Place', 'Delhi')
dictionary : {'Cappaccino': 250, 'Latte': 270, 'Americano': 220, 'Cold Brew': 300, 'Frappuccino': 350, 'Masala Chai': 200, 'Blueberry Muffin': 180, 'Veg Sandwich': 240}

<class 'list'> <class 'tuple'> <class 'set'> <class 'dict'>

In [ ]:
print("first item :", menu[0])
print("last item :", menu[-1])
print("first three item :", menu[0:3])
print("every 2nd item :", menu[::2])
# --- Tuple (same as list) ---
print("\nStore ID         :", store[0])
print("Store city       :", store[2])

# --- Dictionary ---
print("\nPrice of Latte   :", price["Latte"])
print("Safe lookup      :", price.get("Pizza", "Not on menu"))  # no error if key is missing

# --- Set ---
print("\nIs Pune a Starbucks city?  ", "Pune" in cities)
print("Is Jaipur a Starbucks city?", "Jaipur" in cities)

first item : Cappuccino
last item : Cold Brew
first three item : ['Cappuccino', 'Latte', 'Americano']
every 2nd item : ['Cappuccino', 'Americano']

Store ID         : S01
Store city       : Delhi

Price of Latte   : 270
Safe lookup      : Not on menu

Is Pune a Starbucks city?   True
Is Jaipur a Starbucks city? False

In [ ]:
#apply functions to data structure

In [ ]:
# --- Built-in functions on the Revenue list (100 orders) ---

print("Number of orders    :", len(revenue_list))

print("Total revenue       : Rs", round(sum(revenue_list), 2))

print("Average order value: Rs", round(sum(revenue_list) / len(revenue_list), 2))

print("Biggest order       : Rs", max(revenue_list))

print("Smallest order      : Rs", min(revenue_list))

print("Top 5 orders        :", sorted(revenue_list, reverse=True)[:5])

print("Total cups/items    :", sum(qty_list))

NameError: name 'rev_list' is not defined

In [1]:
!pip install seaborn

Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.13/dist-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.13/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->seaborn) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [3]:

#!PIP INSTALL SEABORN PLOTLY OPENPYXL

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df = pd.read_excel("Zomato_India_Orders_Dataset.xlsx", sheet_name = "Orders_Data" )
print("Data Loaded", df.shape[0],"orders and", df.shape[1], "variables")

Data Loaded 200 orders and 15 variables

In [8]:
#attributes

#shape tells us the number of rows and colums
print("shape", df.shape)

#2 columns shows the names of all columns
print("\ncolumns")
print(df.columns)

#index- shows the row labels
print("\n index")
print(df.index)

#data types: tells us the type of data in each column
print("\n Data types")
print(df.dtypes)

#head
print("\nhead")
print(df.head())

shape (200, 15)

columns
Index(['Order_ID', 'Order_Date', 'City', 'Cuisine', 'Customer_Segment',
       'Platform', 'Items_Count', 'Order_Value', 'Discount_Pct',
       'Delivery_Fee', 'Payment_Mode', 'Distance_Km', 'Delivery_Time_Min',
       'Rating', 'Final_Amount'],
      dtype='object')

 index
RangeIndex(start=0, stop=200, step=1)

 Data types
Order_ID                     object
Order_Date           datetime64[ns]
City                         object
Cuisine                      object
Customer_Segment             object
Platform                     object
Items_Count                   int64
Order_Value                   int64
Discount_Pct                float64
Delivery_Fee                  int64
Payment_Mode                 object
Distance_Km                 float64
Delivery_Time_Min             int64
Rating                      float64
Final_Amount                float64
dtype: object

head
  Order_ID Order_Date    City       Cuisine Customer_Segment Platform  \
0   ZM1001 2026-07-01   Delhi       Biryani          Regular      App
1   ZM1002 2026-07-02   Delhi       Biryani          Regular      Web
2   ZM1003 2026-07-03   Delhi  North Indian              New      App
3   ZM1004 2026-07-03  Mumbai  North Indian              New      App
4   ZM1005 2026-07-03    Pune       Burgers             Gold      App

   Items_Count  Order_Value  Discount_Pct  Delivery_Fee Payment_Mode  \
0            3          790           0.0             0         Card
1            4         1160           0.0             0       Wallet
2            3          610           0.0             0          UPI
3            3          650           0.0             0          UPI
4            6         1100           0.1             0         Card

   Distance_Km  Delivery_Time_Min  Rating  Final_Amount
0          5.2                 33     5.0         790.0
1          9.2                 43     3.0        1160.0
2          6.6                 33     4.0         610.0
3          5.8                 39     4.0         650.0
4          8.8                 45     5.0         990.0

In [9]:
# 1.5 Classify the variables (we decide this using the data dictionary)

number_cols = ["Items_Count", "Order_Value", "Discount_Pct", "Delivery_Fee",
               "Distance_Km", "Delivery_Time_Min", "Rating", "Final_Amount"]

category_cols = ["City", "Cuisine", "Customer_Segment", "Platform", "Payment_Mode"]

date_cols = ["Order_Date"]

id_cols = ["Order_ID"]

print("Numerical  :", len(number_cols), number_cols)
print("Categorical:", len(category_cols), category_cols)
print("Date       :", date_cols)
print("ID         :", id_cols)

Numerical  : 8 ['Items_Count', 'Order_Value', 'Discount_Pct', 'Delivery_Fee', 'Distance_Km', 'Delivery_Time_Min', 'Rating', 'Final_Amount']
Categorical: 5 ['City', 'Cuisine', 'Customer_Segment', 'Platform', 'Payment_Mode']
Date       : ['Order_Date']
ID         : ['Order_ID']

In [10]:

# 1.6 Data Quality Check

# 1. Check missing values in each column
print("Missing Values:")
print(df.isnull().sum())

# 2. Check missing values in Rating
print("\nMissing Ratings:")
print(df["Rating"].isnull().sum())

# 3. Check duplicate rows
print("\nDuplicate Rows:")
print(df.duplicated().sum())

# 4. Check whether Order_ID is unique
print("\nAre Order IDs Unique?")
print(df["Order_ID"].is_unique)

Missing Values:
Order_ID             0
Order_Date           0
City                 0
Cuisine              0
Customer_Segment     0
Platform             0
Items_Count          0
Order_Value          0
Discount_Pct         0
Delivery_Fee         0
Payment_Mode         0
Distance_Km          0
Delivery_Time_Min    0
Rating               8
Final_Amount         0
dtype: int64

Missing Ratings:
8

Duplicate Rows:
0

Are Order IDs Unique?
True

In [12]:
#summary statistics
df[number_cols].describe().round(2) #1.

,Items_Count,Order_Value,Discount_Pct,Delivery_Fee,Distance_Km,Delivery_Time_Min,Rating,Final_Amount
count,200.00,200.00,200.00,200.00,200.00,200.00,192.00,200.00
mean,2.77,649.20,0.09,14.15,6.46,39.21,4.03,606.60
std,1.48,510.68,0.07,19.11,3.50,13.82,0.89,460.69
min,1.00,120.00,0.00,0.00,0.50,11.00,1.00,119.00
25%,2.00,310.00,0.00,0.00,3.28,28.75,3.00,309.00
50%,3.00,545.00,0.10,0.00,6.60,39.00,4.00,499.50
75%,4.00,830.00,0.10,30.00,9.70,49.00,5.00,724.00
max,6.00,4850.00,0.20,50.00,12.00,112.00,5.00,4365.00

In [13]:

# 2.2 Statistics for one important column: Final_Amount (what the customer paid)

amount = df["Final_Amount"]

print("Mean (average)     : Rs", round(amount.mean(), 2))
print("Median (middle)    : Rs", amount.median())
print("Mode (most common) : Rs", amount.mode()[0])
print("Minimum            : Rs", amount.min())
print("Maximum            : Rs", amount.max())
print("Standard deviation : Rs", round(amount.std(), 2))
print("Range (max - min)  : Rs", amount.max() - amount.min())

Mean (average)     : Rs 606.6
Median (middle)    : Rs 499.5
Mode (most common) : Rs 410.0
Minimum            : Rs 119.0
Maximum            : Rs 4365.0
Standard deviation : Rs 460.69
Range (max - min)  : Rs 4246.0

In [16]:
#COMPARISON OF MEAN AND median VARIABLE



# Calculate average order amount
mean_value = amount.mean()

# Calculate middle order amount
median_value = amount.median()

print(f"Mean  = Rs {mean_value:.2f}")
print(f"Median = Rs {median_value:.2f}")

# Compare mean and median
if mean_value > median_value:
    print("A few large orders may be pulling the average up.")
else:
    print("The average is close to or below the median.")

Mean  = Rs 606.60
Median = Rs 499.50
A few large orders may be pulling the average up.